# Generated by Django 5.2 on 2025-04-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hearingtestresult",
            name="calibration_data",
            field=models.JSONField(default={}, verbose_name="Данные калибровки"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hearingtestresult",
            name="reliability_1000",
            field=models.FloatField(default=0.0, verbose_name="Достоверность 1000 Гц"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hearingtestresult",
            name="reliability_2000",
            field=models.FloatField(default=0.0, verbose_name="Достоверность 2000 Гц"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hearingtestresult",
            name="reliability_4000",
            field=models.FloatField(default=0.0, verbose_name="Достоверность 4000 Гц"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hearingtestresult",
            name="reliability_500",
            field=models.FloatField(default=0.0, verbose_name="Достоверность 500 Гц"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hearingtestresult",
            name="reliability_8000",
            field=models.FloatField(default=0.0, verbose_name="Достоверность 8000 Гц"),
            preserve_default=False,
        ),
    ]
